import { mkdirSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { readCsv, readText, ROOT, slug, titleCase, toCsv, writeOrCheck, type CsvRecord } from "./common.ts";

const check = Bun.argv.includes("--check");
const generated = "<!-- This file is generated by `bun run catalog:build`. Do not edit directly. -->\n";
const catalog = readCsv("data/catalog.csv");
const categoryOrder = ["official", "operations", "directories", "skills", "integrations", "mcp", "agents", "use-cases", "deployment", "memory", "security", "community", "alternatives"];
const categoryCopy: Record<string, string> = {
  official: "Primary project resources maintained by OpenClaw.",
  operations: "Documentation for installing, configuring, and operating an OpenClaw Gateway.",
  directories: "Deeper community-maintained catalogs for focused discovery.",
  skills: "Skill registries and guidance for extending OpenClaw capabilities.",
  integrations: "Plugins, channels, and integrations that connect OpenClaw to other systems.",
  mcp: "Model Context Protocol servers and adapters that can complement agent workflows.",
  agents: "Agent orchestration, personas, and workspace customization.",
  "use-cases": "Runnable examples and practical patterns for applying OpenClaw.",
  deployment: "Packaging, hosting, isolation, and secure remote operations.",
  memory: "Memory, session, context, and observability resources.",
  security: "Security policy, hardening, disclosure, and trust resources.",
  community: "Support, learning, issue tracking, and release resources.",
  alternatives: "Related and alternative personal-agent projects.",
};
const categoryLabels: Record<string, string> = { mcp: "MCP" };

function categoryLabel(category: string): string {
  return categoryLabels[category] ?? titleCase(category);
}

function marker(record: CsvRecord): string {
  return `${record.officiality === "official" ? " 🎖️" : ""}${record.pricing === "paid" ? " 💵" : ""}`;
}

function simpleEntry(record: CsvRecord): string {
  return `- [${record.name}](${record.url}) - ${record.description}.${marker(record)}`;
}

function detailedEntry(record: CsvRecord): string {
  const metadata = [record.kind, record.officiality, record.pricing, record.status].join(" · ");
  const evidence = record.repository_url ? ` [repository](${record.repository_url})` : "";
  const risk = record.risk_notes ? `\n  - Risk: ${record.risk_notes}.` : "";
  return `- [${record.name}](${record.url}) - ${record.description}.${marker(record)}\n  - Metadata: \`${metadata}\`; last verified ${record.last_verified}.${evidence}${risk}`;
}

function grouped(records: CsvRecord[], detailed: boolean): string {
  const groups = new Map<string, CsvRecord[]>();
  for (const record of records) {
    const group = record.subcategory || "general";
    groups.set(group, [...(groups.get(group) ?? []), record]);
  }
  return [...groups.entries()].map(([group, items]) => {
    const heading = !detailed || group === "general" ? "" : `## ${titleCase(group)}\n\n`;
    return `${heading}${items.map(detailed ? detailedEntry : simpleEntry).join("\n\n")}`;
  }).join("\n\n");
}

function buildReadme(byCategory: Map<string, CsvRecord[]>): string {
  const categories = categoryOrder.filter((category) => byCategory.has(category));
  const toc = categories.map((category) => `- [${categoryLabel(category)}](#${category})`).join("\n");
  const sections = categories.map((category) => `## ${categoryLabel(category)}\n\n${categoryCopy[category]}\n\n${grouped(byCategory.get(category)!, false)}`).join("\n\n");
  return `${generated}# Awesome OpenClaw [![Awesome](https://awesome.re/badge.svg)](https://github.com/sindresorhus/awesome) ![CI](https://img.shields.io/badge/CI-GitHub%20Actions-blue?logo=github-actions) [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)](CONTRIBUTING.md)\n\nA comprehensive catalog of OpenClaw resources and practical playbooks. The catalog covers official documentation, skills, integrations, deployments, security guidance, use cases, and related projects.\n\nThis is an independent community list. Inclusion is not an endorsement, security audit, or guarantee of maintenance. OpenClaw resources can execute code, access credentials, send messages, and change external systems, so review every project before installing or connecting it.\n\n## How to use this catalog\n\n- Browse the [full catalog index](content/catalog/index.md) for richer metadata, risk notes, and verification dates.\n- Follow the [practical playbooks](content/playbook/index.md) for task-based setup and operating procedures.\n- Treat [data/catalog.csv](data/catalog.csv) and the playbook frontmatter as the source of truth; generated Markdown is checked for drift.\n- Read [CONTRIBUTING.md](CONTRIBUTING.md) before adding or changing a record.\n\n## Contents\n\n${toc}\n- [Practical playbooks](content/playbook/index.md)\n- [Contributing](CONTRIBUTING.md)\n- [License](LICENSE)\n\n${sections}\n\n## Practical playbooks\n\nUse the [playbook index](content/playbook/index.md) to find tested task guides for onboarding, safe operations, skills, deployment, and recovery.\n\n## Contributing\n\nPlease read [CONTRIBUTING.md](CONTRIBUTING.md) before proposing a resource or playbook.\n\n## License\n\nThe curation and original text in this repository are dedicated to the public domain under [CC0 1.0](LICENSE). Third-party resources linked here retain their own licenses.\n`;
}

function buildCatalogPages(byCategory: Map<string, CsvRecord[]>): void {
  const categories = categoryOrder.filter((category) => byCategory.has(category));
  const index = `${generated}# Catalog index\n\nStructured catalog records are stored in [data/catalog.csv](../../data/catalog.csv) and published here with metadata, verification dates, and risk notes.\n\n${categories.map((category) => `- [${categoryLabel(category)}](./${category}.md) - ${byCategory.get(category)!.length} records. ${categoryCopy[category]}`).join("\n")}\n`;
  writeOrCheck("content/catalog/index.md", index, check);
  for (const category of categories) {
    const content = `${generated}# ${categoryLabel(category)}\n\n${categoryCopy[category]}\n\n${grouped(byCategory.get(category)!, true)}\n\n[Back to catalog index](index.md)\n`;
    writeOrCheck(`content/catalog/${category}.md`, content, check);
  }
}

async function readPlaybooks(): Promise<{ meta: CsvRecord; body: string; path: string }[]> {
  const directory = resolve(ROOT, "content/playbook");
  const files = readdirSync(directory).filter((name) => name.endsWith(".md") && name !== "index.md").sort();
  const guides = [];
  for (const file of files) {
    const path = resolve(directory, file);
    const text = await Bun.file(path).text();
    const end = text.indexOf("\n---\n", 4);
    if (!text.startsWith("---\n") || end === -1) throw new Error(`${file} must have YAML frontmatter`);
    const meta: CsvRecord = {};
    for (const line of text.slice(4, end).split("\n")) {
      const separator = line.indexOf(":");
      meta[line.slice(0, separator).trim()] = line.slice(separator + 1).trim().replace(/^['"]|['"]$/g, "");
    }
    meta.path = `content/playbook/${file}`;
    guides.push({ meta, body: text.slice(end + 6), path: file });
  }
  const order = new Map(["Foundation", "Operations", "Skills and automation", "Deployment", "Security and recovery", "Advanced"].map((value, index) => [value, index]));
  return guides.sort((a, b) => (order.get(a.meta.track) ?? 99) - (order.get(b.meta.track) ?? 99) || a.meta.title.localeCompare(b.meta.title));
}

async function buildPlaybooks(): Promise<void> {
  const guides = await readPlaybooks();
  const headers = ["id", "title", "track", "summary", "audience", "difficulty", "status", "prerequisites", "related_catalog_ids", "requires_credentials", "external_write", "tested_on", "last_verified", "path"];
  writeOrCheck("data/playbook.csv", toCsv(guides.map(({ meta }) => meta), headers), check);
  const tracks = new Map<string, typeof guides>();
  for (const guide of guides) tracks.set(guide.meta.track, [...(tracks.get(guide.meta.track) ?? []), guide]);
  const body = [...tracks.entries()].map(([track, items]) => `## ${track}\n\n${items.map(({ meta }) => `- [${meta.title}](${meta.path.replace("content/playbook/", "")}) - ${meta.summary} (${meta.difficulty}; ${meta.status})`).join("\n")}`).join("\n\n");
  writeOrCheck("content/playbook/index.md", `${generated}# Practical playbooks\n\nThese task-based guides are runnable starting points. Test them in a disposable environment, review credentials and external writes, and adapt commands to the versions in use.\n\n${body}\n\nPlaybook records are generated into [data/playbook.csv](../../data/playbook.csv).\n`, check);
}

const byCategory = new Map<string, CsvRecord[]>();
for (const record of catalog) byCategory.set(record.category, [...(byCategory.get(record.category) ?? []), record]);
for (const records of byCategory.values()) records.sort((a, b) => a.subcategory.localeCompare(b.subcategory) || a.name.localeCompare(b.name) || a.id.localeCompare(b.id));
mkdirSync(resolve(ROOT, "content/catalog"), { recursive: true });
mkdirSync(resolve(ROOT, "content/playbook"), { recursive: true });
writeOrCheck("README.md", buildReadme(byCategory), check);
buildCatalogPages(byCategory);
await buildPlaybooks();
console.log(`${check ? "Checked" : "Built"} ${catalog.length} catalog records and generated catalog/playbook Markdown surfaces.`);
